SELECT * FROM Staff
SELECT * FROM GeneralStaff
SELECT * FROM DeliveryStaff
SELECT * FROM AreaCode
SELECT * FROM Customers
SELECT * FROM Order
SELECT * FROM Menu
SELECT * FROM Beverage
SELECT * FROM Food
SELECT * FROM Assigned_to
SELECT * FROM Delivers_to
SELECT * FROM Done_by
SELECT * FROM Used_to
SELECT * FROM Lives_in
SELECT * FROM Comes_from
SELECT * FROM Fulfills